name: Build HyperCE Driver

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Install WDK and SDK
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          
          choco install windowsdriverkit10 -y
          
      - name: Setup Environment and Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          
          set WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10
          set WindowsSdkVersion=10.0.20348.0
          
          msbuild hv.sln /p:Configuration=Release /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0.20348.0 /p:UseDebugLibraries=false /p:OutDir=output\
          
      - name: Upload Driver
        uses: actions/upload-artifact@v4
        with:
          name: HyperCE-Driver
          path: |
            **/*.sys
            **/output/*.sys
            **/*.exe
