name: Build HyperCE Driver

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Install Multiple WDK and SDK Versions
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          
          choco install windows-sdk-10-version-2104-all -y  # 10.0.20348.0
          choco install windows-sdk-10.0 -y
          
          choco install windowsdriverkit10 -y
          
          choco install visualstudio2022-workload-vctools -y
      
      - name: Try Different SDK Versions
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          
          msbuild hv.sln /p:Configuration=Release /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0.20348.0 /p:UseDebugLibraries=false /p:OutDir=output\20348\
          
          msbuild hv.sln /p:Configuration=Release /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0.19041.0 /p:UseDebugLibraries=false /p:OutDir=output\19041\
          
          msbuild hv.sln /p:Configuration=Release /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0.22621.0 /p:UseDebugLibraries=false /p:OutDir=output\22621\
          
          msbuild hv.sln /p:Configuration=Release /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0.17763.0 /p:UseDebugLibraries=false /p:OutDir=output\17763\
          
          msbuild hv.sln /p:Configuration=Release /p:Platform=x64 /p:UseDebugLibraries=false /p:OutDir=output\auto\
      
      - name: Upload Any Built Drivers
        uses: actions/upload-artifact@v4
        with:
          name: HyperCE-Driver-All-Versions
          path: |
            **/*.sys
            **/output/**/*.sys
            **/*.exe
