name: Build HyperCE Driver

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Setup Windows SDK and WDK
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          
          choco install windows-driver-kit -y --version 10.0.22621.2428
          
          choco install windows-sdk-10-version-2104-all -y
      
      - name: Build Driver
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\SetEnv.cmd" /release /x64 /win10
          
          msbuild hv.sln /p:Configuration=Release /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0.22621.0
          
      - name: Upload Driver
        uses: actions/upload-artifact@v4
        with:
          name: HyperCE-Driver
          path: |
            **/*.sys
            **/*.exe
