name: Build HyperCE Driver

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Setup Windows SDK
        run: |

          choco install windows-sdk-10-version-2104-all
          
      - name: Build Driver
        run: |
          # Компилируем драйвер
          msbuild hv.sln /p:Configuration=Release /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0.20348.0
          
      - name: Upload Driver
        uses: actions/upload-artifact@v4
        with:
          name: HyperCE-Driver
          path: |
            **/*.sys
            **/*.exe
